use libreriaonline;

INSERT INTO provincia(nombre) VALUES('Nuevo león'),
                                ('Jalisco'),
                                ('Chiapas'),
                                ('Sonora'),
                                ('Sinaloa'),
                                ('Aguascalientes'),
                                ('Guanajuato'),
                                ('Estado de México'),
                                ('Michoacán'),
                                ('Yucatán');

INSERT INTO localidad(nombre, id_provincia) VALUES ('Monterrey', 1),
                                                ('Escobedo',1),
                                                ('Guadalajara',2),
                                                ('El Salto',2),
                                                ('Chiapa de Corzo',3),
                                                ('La Libertad',3),
                                                ('Mazatán',4),
                                                ('Hermosillo',4),
                                                ('Culiacán',5),
                                                ('Mazatlán',5),
                                                ('Aguascalientes',6),
                                                ('Asientos',6),
                                                ('Guanajuato',7),
                                                ('San Miguel de Allende',7),
                                                ('Ecatepect de Morelos',8),
                                                ('Metepec',8),
                                                ('Morelia',9),
                                                ('Hidalgo',9),
                                                ('Mérida',10),
                                                ('Cuzamá',10);

INSERT INTO direccion(calle,colonia,codigo_postal,id_localidad)
    VALUES
     ('calle1','colonia1',12432,1),
     ('calle2','colonia2',12432,2),
     ('calle3','colonia3',12432,3),
     ('calle4','colonia4',12432,4),
     ('calle5','colonia5',12432,5),
     ('calle6','colonia6',12432,6),
     ('calle7','colonia7',12432,7),
     ('calle8','colonia8',12432,8),
     ('calle9','colonia9',12432,9),
     ('calle10','colonia10',12432,10),
     ('calle11','colonia11',12432,11),
     ('calle12','colonia12',12432,12),
     ('calle13','colonia13',12432,13),
     ('calle14','colonia14',12432,14),
     ('calle15','colonia15',12432,15),
     ('calle16','colonia16',12432,16),
     ('calle17','colonia17',12432,17),
     ('calle18','colonia18',12432,18),
     ('calle19','colonia19',12432,19),
     ('calle20','colonia20',12432,20),
     ('calle21','colonia21',12432,1),
     ('calle22','colonia22',12432,2),
     ('calle23','colonia23',12432,3),
     ('calle24','colonia24',12432,4);


INSERT INTO persona(nombre,apellido1,id_direccion) VALUES('Laura','Esquivel',1),
                                                        ('Juan', 'Villoro', 2),
                                                        ('Valeria', 'Luiselli', 3),
                                                        ('Guadalupe', 'Nettel', 4),
                                                        ('Gabriel', 'García', 5),
                                                        ('Octavio', 'Paz', 6),
                                                        ('Juan', 'Rulfo', 7),
                                                        ('Juan José', 'Arreola', 8),
                                                        ('Rosario', 'Castellanos', 9),
                                                        ('Carlos', 'Monsiváis', 10),
                                                        ('Cliente1' , 'Apellido1', 11),
                                                        ('Cliente2' , 'Apellido2', 12),
                                                        ('Cliente3' , 'Apellido3', 13),
                                                        ('Cliente4' , 'Apellido4', 14),
                                                        ('Cliente5' , 'Apellido5', 15),
                                                        ('Cliente6' , 'Apellido6', 16),
                                                        ('Cliente7' , 'Apellido7', 17),
                                                        ('Cliente8' , 'Apellido8', 18),
                                                        ('Cliente9' , 'Apellido9', 19),
                                                        ('Cliente10' , 'Apellido10', 20);
                                                



INSERT INTO autor(url_web,id_persona) VALUES('www.LauraEsquivel.com',1),
                                            ('www.JuanVilloro.com', 2),
                                            ('www.ValeriaLuiselli.com', 3),
                                            ('www.GuadalupeNettel.com', 4),
                                            ('www.GabrielGarcía.com', 5),
                                            ('www.OctavioPaz.com', 6),
                                            ('www.JuanRulfo.com', 7),
                                            ('www.JuanJoséArreola.com', 8),
                                            ('www.RosarioCastellanos.com', 9),
                                            ('www.CarlosMonsiváis.com', 10);

INSERT INTO cliente(email,telefono,id_persona) VALUES ('cliente1@gamil.com',1234567,11),
                                                    ('cliente2@gmail.com', 1234567,12),
                                                    ('cliente3@gmail.com', 1234567,13),
                                                    ('cliente4@gmail.com', 1234567,14),
                                                    ('cliente5@gmail.com', 1234567,15),
                                                    ('cliente6@gmail.com', 1234567,16),
                                                    ('cliente7@gmail.com', 1234567,17),
                                                    ('cliente8@gmail.com', 1234567,18),
                                                    ('cliente9@gmail.com', 1234567,19),
                                                    ('cliente10@gmail.com', 1234567,20);


INSERT INTO editorial(nombre,url_web,telefono,id_direccion) VALUES ('Caligrama Editores','www.CaligramaEditores.com',1234567,21),
                                                                    ('Editorial el Naranjo','www.EditorialNaranjo.com',1234567,22);
                                                    

INSERT INTO libro(titulo, descripcion, ISBN, año_publicacion,tipo,id_editorial)
            VALUES('Como agua para chocolate', 'La historia está ambientada en Piedras Negras, Coahuila, México. Situada en la época de la Revolución mexicana (Pueblo oprimido, representación ambiental de los personajes: Tita y Pedro: Oprimidos; Mamá Elena y Rosaura: opresores; Gertrudis: Revolución (cambio - libertad)).La historia empieza con el nacimiento de Tita la última de tres hermanas. A Tita se le escuchaba llorar ya desde el vientre, cuándo nació lloraba y lo único que la calmaba era el olor a sopa, por eso siempre estaba con Nacha, la cocinera. A los 15 años Tita se enamoró de un chico llamado Pedro, y éste a su vez, correspondió su amor. Pedro fue a pedirle la mano de Tita, pero Mamá Elena no se la concedió, pero sí la de Rosaura, debido a que Tita siendo la menor, estaba obligada a cuidar de ella hasta su muerte, provocando así la rabia y el dolor de Tita. Pedro acepta para poder estar cerca de Tita. Pedro y Rosaura tienen un hijo pero Rosaura no se puede hacer cargo del niño, ya que estaba muy enferma, la nodriza muere y la única que se puede hacer cargo del niño es Tita. Mamá Elena sospechaba de que Pedro y Tita se veían, así que mandó a Pedro y a Rosaura a la ciudad, e l niño muere y Tita se vuelve medio loca y su madre decide mandarla con el doctor John a la ciudad y surge un amor entre ellos dos, sin embargo, Tita tiene que regresar para cuidar de su madre. Pedro y Rosaura regresan y a Tita le surge un problema: casarse con John, quien le promete un amor puro y sincero, o seguirse envolviendo apasionadamente de forma ilícita con Pedro. Como agua para chocolate es narrada por la nieta de Tita, la hija de Esperanza y Alex',
            'ISBN1','1989','papel/ebook',1),
            ('La ley del amor','descripcion', 'ISBN2','1995','papel/ebook',1),
            ('El disparo de argón','descripcion', 'ISBN3','2005','papel/ebook',1),
            ('Materia dispuesta','descripcion', 'ISBN4','1997','papel/ebook',1),
            ('Los ingrávidos','descripcion', 'ISBN5','2011','papel/ebook',1),
            ('La historia de mis dientes','descripcion', 'ISBN6','2013','papel/ebook',1),
            ('El huésped','descripcion', 'ISBN7','2006','papel/ebook',1),
            ('El cuerpo en que nací','descripcion', 'ISBN8','2011','papel/ebook',1),
            ('El amor en los tiempos del cólera','descripcion', 'ISBN9','1985','papel/ebook',1),
            ('Del amor y otros demonios','descripcion', 'ISBN10','1994','papel/ebook',1),
            ('Luna silvestre','descripcion', 'ISBN11','1933','ebook',2),
            ('¡No pasarán!','descripcion', 'ISBN12','1936','ebook',2),
            ('El Llano en llamas','descripcion', 'ISBN13','1950','ebook',2),
            ('La cuesta de las comadres','descripcion', 'ISBN14','1948','ebook',2),
            ('Gunter Stapenhorst','descripcion', 'ISBN15','1946','ebook',2),
            ('La palabra educación','descripcion', 'ISBN16','1973','papel',2),
            ('Balún Canán','descripcion', 'ISBN17','2011','papel',2),
            ('Rito de iniciación','descripcion', 'ISBN18','1996','papel',2),
            ('Principados y potestades ','descripcion', 'ISBN19','1969','papel',2),
            ('Protestantismo, diversidad y tolerancia','descripcion', 'ISBN20','2002','papel',2);

INSERT INTO ebook(tamaño_archivo,precio,id_libro)
            VALUES(50,200,1),
                (35,200,2),
                (35,200,3),
                (30,250,4),
                (45,230,5),
                (35,400,6),
                (36,500,7),
                (25,600,8),
                (65,100,9),
                (65,300,10),
                (05,250,11),
                (15,230,12),
                (35,800,13),
                (36,700,14),
                (35,50,15);

INSERT INTO papel(lugar_impresion,fecha_impresion,precio,id_libro)
           VALUES('México','2020-02-01',500,1),
                ('México','2020-02-02',500,2),
                ('México','2020-03-02',300,3),
                ('México','2020-02-04',500,4),
                ('México','2020-05-02',900,5),
                ('México','2020-02-26',500,6),
                ('México','2020-12-02',500,7),
                ('México','2020-11-02',700,8),
                ('México','2020-04-02',400,9),
                ('México','2020-12-02',500,10),
                ('México','2020-01-02',500,16),
                ('México','2020-01-10',500,17),
                ('México','2020-10-06',500,18),
                ('México','2020-09-07',500,19),
                ('México','2020-08-08',500,20);

INSERT INTO autor_libro(id_autor,id_libro)
            VALUES(1,1),
                (1,2),
                (2,3),
                (2,4),
                (3,5),
                (3,6),
                (4,7),
                (4,8),
                (5,9),
                (5,10),
                (6,11),
                (6,12),
                (7,13),
                (7,14),
                (8,15),
                (8,16),
                (9,17),
                (9,18),
                (10,19),
                (10,20);

INSERT INTO almacen(telefono,id_direccion)
            VALUES(12344567,23),
                  (12344567,24);

INSERT INTO almacen_papel(id_almacen,id_papel,stock)
            VALUES(1,1,50),
                  (1,2,50),
                  (1,3,50),
                  (1,4,50),
                  (1,5,50),
                  (1,6,50),
                  (1,7,50),
                  (1,8,50),
                  (1,9,50),
                  (1,10,50),
                  (2,11,50),
                  (2,12,50),
                  (2,13,50),
                  (2,14,50),
                  (2,15,50);

INSERT INTO carrito(fecha_compra,id_cliente)
            VALUES ('2020-01-01 12:00:00',1),
                   ('2020-01-01 13:00:00',2),
                   ('2020-01-01 14:00:00',3),
                   ('2020-01-01 15:00:00',4),
                   ('2020-01-01 16:00:00',5),
                   ('2020-01-01 17:00:00',6),
                   ('2020-01-01 18:00:00',7),
                   ('2020-01-01 19:00:00',8),
                   ('2020-01-01 12:00:00',9),
                   ('2020-01-01 20:00:00',10),
                   ('2020-01-01 21:00:00',1),
                   ('2020-01-02 12:00:00',2),
                   ('2020-01-03 12:00:00',3),
                   ('2020-01-04 12:00:00',4),
                   ('2020-01-05 12:00:00',5);

INSERT INTO carrito_libro(id_carrito,id_libro,cantidad)
            VALUES (1,1,1),
                   (2,2,1),
                   (3,3,1),
                   (4,4,1),
                   (5,5,1),
                   (6,6,1),
                   (7,7,1),
                   (8,8,1),
                   (9,9,1),
                   (10,10,1),
                   (11,11,2),
                   (12,12,2),
                   (13,13,2),
                   (14,14,2),
                   (15,15,2);